### ISSUE TITLE
PROBLEMAS

### ISSUE THREAD

**Issue by anacarolina-peregrino** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2024-2-ment2-noite1-idosos-1#4]

**Comment by Jgustavo98** [comment]
Aqui vou falar do problema  ?

**Comment by Joaogustavopires** [comment]
Fiz préviamente algumas perguntas  referente ao problemas que podemos enfrentar, afim de futuramente podermos solucionar o mesmo.
