### ISSUE TITLE
HISTÓRIA DE USUÁRIOS

### ISSUE THREAD

**Issue by anacarolina-peregrino** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2024-2-ment2-noite1-idosos-1#6]

**Comment by gustavo-vb** [comment]
Me adicionei como responsável pela criação das histórias de usuário, visto que o novo integrante do grupo ainda não se manifestou.

**Comment by gustavo-vb** [comment]
Adicionadas seis **Histórias de Usuário** ao projeto _(duas histórias por Persona)_ como solicitado em sala.
